config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "homes#top"
  get "home/about" => "homes#about"
  resources :books, only:[:index, :create, :show, :edit, :update, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only:[:index, :show, :edit, :update]
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body ,presence: true
  validates :body, length: {maximum: 200}

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book=Book.new
    @books=Book.all
  end

  def create
    @book=Book.new(book_params)
    @book.user_id=current_user.id
    @books=Book.all
    if @book.save
      redirect_to book_path(@book.id)
      flash[:notice]="You have created book successfully."
    else
      render :index
    end
  end

  def show
    @book=Book.new
    @books=Book.find(params[:id])
    @user=User.find_by(id: @books.user_id)
    @book_comment=BookComment.new
    @book_comments=@books.book_comments
  end

  def edit
    @book=Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book=Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id)
      flash[:notice]="You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    @book=Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_comment_form.html.erb
<%= form_with(model: [book, book_comment], remote: true) do |f| %>
  <%= f.text_area :comment, row: "5" %>
  <%= f.submit "送信" %>
<% end %>

app/views/books/_comment_index.html.erb
<table>
  <tbody>
    <% book_comment.each do |book_comment| %>
      <tr>
        <td>
          <%= link_to user_path(book_comment.user.id) do %>
            <%= attachment_image_tag book_comment.user, :profile_image, size: "40x40", fallback: "no_image.jpeg" %><br />
            <%= book_comment.user.name %>
          <% end %>
        </td>
        <td><%= book_comment.comment %></td>
        <td>
          <% if book_comment.user == current_user %>
            <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, class: "btn btn-sm btn-danger" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_favorites.html.erb
<% if book.favorited_by?(current_user) %>
<p>
  <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
    ♥<%= book.favorites.count %>
  <% end %>
</p>
<% else %>
<p>
  <%= link_to book_favorites_path(book), method: :post, remote: true do %>
    ♡<%= book.favorites.count %>
  <% end %>
</p>
<% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>

      <%= form_with model: @book, local: true do |f| %>
        <%= render "layouts/error_form", model: f.object %>

        <div class="form-group">
          <label>Title</label>
          <%= f.text_field :title, class: "form-control" %>
        </div>

        <div class="form-group">
          <label>Opinion</label>
          <%= f.text_area :body, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.submit "Update Book", class: "btn btn-success" %>
        </div>
      <% end %>

      <%= link_to "Show", book_path(@book.id) %>
       |
      <%= link_to "Back", books_path %>

    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <%= render "layouts/error_form", model: @book %>
  <div class="row">
    <div class="col-md-3">
      <%= render partial: "layouts/user_info", locals: {user: current_user} %>
      <%= render partial: "layouts/new_book", locals: {book: @book} %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>

      <table class="table table-hober table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user.id) do %>
                <%= attachment_image_tag book.user, :profile_image, size: "40x40", fallback: "no_image.jpeg" %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
            <td id="favorite_button_<%= book.id %>"><%= render "favorites", book: book %></td>
            <td>コメント数: <%= book.book_comments.count %></td>
          </tr>
          <% end %>
        </tbody>

      </table>
    </div>

  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render partial: "layouts/user_info", locals: {user: @user} %>
      <%= render partial: "layouts/new_book", locals: {book: @book} %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>

      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
                <%= attachment_image_tag @user, :profile_image, size: "40x40", fallback: "no_image.jpeg" %><br />
                <%= @user.name %>
              <% end %>
            </td>
            <td><%= link_to @books.title, book_path(@books.id) %></td>
            <td><%= @books.body %></td>
            <td id="favorite_button_<%= @books.id %>"<%= render "favorites", book: @books %></td>
            <td>コメント数: <%= @books.book_comments.count %></td>
            <% if @user.id == current_user.id %>
            <td><%= link_to "Edit", edit_book_path(@books.id), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to "Destroy", book_path(@books.id), method: :delete, class: "btn btn-sm btn-danger" %></td>
            <% end %>
          </tr>
        </tbody>
      </table>

      <div id="comment_index">
        <%= render "books/comment_index", book_comment: @book_comments %>
      </div>

      <div id="new-comments">
        <%= render "comment_form", book: @books, book_comment: @book_comment %>
      </div>

    </div>
  </div>
</div>